// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3NXtxONa7awVuUOxHXGG2RByw39RmrkQ',
    appId: '1:192936358262:web:ee2b059f9210133c318a57',
    messagingSenderId: '192936358262',
    projectId: 'registration-3d512',
    authDomain: 'registration-3d512.firebaseapp.com',
    databaseURL: 'https://registration-3d512-default-rtdb.firebaseio.com',
    storageBucket: 'registration-3d512.firebasestorage.app',
    measurementId: 'G-2V2LF4VR3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIW-Hj1ceS8VJNY7T8Ti7RlmtOOpn5yLI',
    appId: '1:192936358262:android:41a65f742aeec9de318a57',
    messagingSenderId: '192936358262',
    projectId: 'registration-3d512',
    databaseURL: 'https://registration-3d512-default-rtdb.firebaseio.com',
    storageBucket: 'registration-3d512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBktuUNz4mnvOEvPnJYl1YnU3ZhfVMUmxM',
    appId: '1:192936358262:ios:3ed963bd115b9ba0318a57',
    messagingSenderId: '192936358262',
    projectId: 'registration-3d512',
    databaseURL: 'https://registration-3d512-default-rtdb.firebaseio.com',
    storageBucket: 'registration-3d512.firebasestorage.app',
    iosBundleId: 'com.meta.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBktuUNz4mnvOEvPnJYl1YnU3ZhfVMUmxM',
    appId: '1:192936358262:ios:3ed963bd115b9ba0318a57',
    messagingSenderId: '192936358262',
    projectId: 'registration-3d512',
    databaseURL: 'https://registration-3d512-default-rtdb.firebaseio.com',
    storageBucket: 'registration-3d512.firebasestorage.app',
    iosBundleId: 'com.meta.registration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3NXtxONa7awVuUOxHXGG2RByw39RmrkQ',
    appId: '1:192936358262:web:c0420116a5d25215318a57',
    messagingSenderId: '192936358262',
    projectId: 'registration-3d512',
    authDomain: 'registration-3d512.firebaseapp.com',
    databaseURL: 'https://registration-3d512-default-rtdb.firebaseio.com',
    storageBucket: 'registration-3d512.firebasestorage.app',
    measurementId: 'G-FZV03FR2QW',
  );
}
